#!/usr/bin/env just --justfile
# do not echo commands
set quiet
# default is showing list of commands
set default-list := true
# do not evaluate parameters if you don't need them
set lazy

# import the template updater : disabled on packaged tool
mod template

template := env("OS_TEMPLATE", "./template/src")
commands := env("OS_CMD", module_directory() + "/cmd.sh")

# initialize directory as a nonOS config
[no-cd]
init target="./" : (_generate target) (_fixup target)

# format nix files in the provided directory
format directory :
     "{{commands}}" format "{{directory}}"

# build target configuration locally
[no-cd]
build config:
    "{{commands}}/build.sh" "{{config}}"

################# Private recipes #################

_update-pin d:
    npins -d "{{d}}/npins" update nonOS

_hardware-config d :
    "{{commands}}" hardware_config "{{d}}"

_template-config d :
    "{{commands}}" copy_template "{{template}}" "{{d}}"

[parallel]
_generate d: (_template-config d) (_hardware-config d)

[parallel]
_fixup d : (format d) (_update-pin d)


