# need nix package "nixos-install-tools" and "nixos-install"

# provided by python
from asyncio import Task, sleep
from pathlib import Path
from re import DOTALL, MULTILINE, sub
from sys import argv

# provided by uv
from commands.nixformat import nixformat
from shellous import ResultError, sh  # pyright: ignore [reportMissingImports]
from aiofiles import open # pyright: ignore [reportMissingImports]

# provided by us
from commands.progress import Progress
from commands.exceptions import ShellException, assert_cmd

APPNAME = argv[0]

class nixos_generate_config(Task) :

    def __init__(self, file: Path | str = "", display :bool = True) -> None :
        """
            'nixos-generate-config --show-hardware-config --no-filesystems'
            this command does not really take any time. but for consistency,
            we run it async
        """
        assert_cmd("nixos-generate-config")
        self.file = Path(file).resolve()
        self.file.parent.mkdir(parents=True, exist_ok=True)
        self._display = display


    async def _execute(self) :
        """ run the generate config and write the file to target directory """
        hardwareconfig = ""
        if self._display :
            async with Progress("auto-detecting hardware config") as progress:
                with progress.info("generating config") :
                    hardwareconfig = await self._generate_config()
                    await sleep(0.1)
                with progress.info("removing imports") :
                    hardwareconfig = self._pre_write_fixup(hardwareconfig)
                    await sleep(0.1)
                with progress.info("writing hardware-config to file") :
                    await self._write_config(hardwareconfig)
                    await sleep(0.1)
                with progress.info("cleaning file in place") :
                    await nixformat(self.file)
                    await sleep(0.1)
        else :
            hardwareconfig = await self._generate_config()
            hardwareconfig = self._pre_write_fixup(hardwareconfig)
            await self._write_config(hardwareconfig)

    def __await__(self) :
        """ make object awaitable """
        return self._execute().__await__()

    @staticmethod
    async def _generate_config() -> str:
        cmd = sh([
        "nixos-generate-config",
        "--show-hardware-config",
        "--no-filesystems"
        ])
        try:
            return await cmd()
        except ResultError as exc:
            raise ShellException(cmd, exc)

    @staticmethod
    def _pre_write_fixup(nix : str) -> str:
        """ remove commentns and imports before writing to file """
        nix = sub(r"imports\s*=\s*\[(?:.*?)\]\s*;", "", nix, flags=DOTALL) # remove imports from installer
        nix = sub(r'^\s*#.*\n?', '', nix, flags=MULTILINE) # remove comments
        nix = f"# Generated by ‘{APPNAME}’,\n# Do not modify this file!\n# it may be overriden during updates\n{nix}"
        return nix

    async def _pos_write_fixup(self) :
        fixups = [
            sh(["deadnix","-eq", f'"{self.file}"']),
            sh(["alejandra","-q", f'"{self.file}"']),
            sh(["nixfmt","-qs", f'"{self.file}"'])
        ]
        for f in fixups :
            try :
              await f()
            except ResultError:
                pass # ignore formatter errors




    async def _write_config(self, hardwareconfig: str) :
        async with open(self.file, "w") as f:
            await f.write(hardwareconfig)
