# hardware-configuration.nix
# generate with 'nixos-generate-config'
#	It was generated by ‘nixos-generate-config’
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

   fileSystems."/" = {
    device = "nixos-pool/local/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "nixos-pool/local/nix";
    fsType = "zfs";
    neededForBoot = true;
  };

  fileSystems."/nix/persist" = {
    device = "nixos-pool/safe/persist";
    fsType = "zfs";
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "nixos-pool/safe/home";
    fsType = "zfs";
  };

  # TODO : make sure that the uuid is 8001-EF00
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8001-EF00";
    fsType = "vfat";
  };
}