{ config, pkgs, ... }:

{
    # Import other configuration modules
    # (hardware-configuration.nix is autogenerated upon installation)
    # paths in nix expressions are always relative the file which defines them
    imports = [
        ./hardware-configuration.nix
    ];

    # Name your host machine
    networking.hostName = "mymachine";

    # Set your time zone.
    time.timeZone = "Europe/Utrecht";

    # Enter keyboard layout
    services.xserver.layout = "us";
    services.xserver.xkbVariant = "altgr-intl";

    # Define user accounts
    users.users.myuser = {
      extraGroups = [ "wheel" "networkmanager" ];
      isNormalUser = true;
    };

    # Install some packages
    environment.systemPackages = with pkgs; [
      ddate
      testdisk
    ];

    # Enable the OpenSSH daemon
    services.openssh.enable = true;

}
