# need nix package "nixos-install-tools" and "nixos-install"

# python
from asyncio import sleep

# ours
from cmd.awaitable import Awaitable
from cmd.exceptions import ShellException, assert_cmd
from cmd.nixformat import nixformat
from pathlib import Path
from re import DOTALL, MULTILINE, sub
from sys import argv
from typing import Any

from aiofiles import open  # pyright: ignore [reportMissingImports]

# uv
from shellous import ResultError, sh  # pyright: ignore [reportMissingImports]
from tui import Progress

APPNAME = argv[0]


class nixos_generate_config(Awaitable):
    def __init__(self, file: Path | str = "", display: bool = True) -> None:
        """
        'nixos-generate-config --show-hardware-config --no-filesystems'
        this command does not really take any time. but for consistency,
        we run it async
        """
        assert_cmd("nixos-generate-config")
        self.file = Path(file).resolve()
        self.file.parent.mkdir(parents=True, exist_ok=True)
        self._display = display

    async def _exec(self):
        """run the generate config and write the file to target directory"""
        hardwareconfig = ""

        async def _generate_config(*args) -> str:
            cmd = sh(["nixos-generate-config", "--show-hardware-config", "--no-filesystems"])
            try:
                return await cmd()
            except ResultError as exc:
                raise ShellException(cmd, exc)

        async def _pre_write_fixup(nix: str) -> str:
            """remove commentns and imports before writing to file"""
            nix = sub(
                r"imports\s*=\s*\[(?:.*?)\]\s*;", "", nix, flags=DOTALL
            )  # remove imports from installer
            nix = sub(r"^\s*#.*\n?", "", nix, flags=MULTILINE)  # remove comments
            nix = f"# Generated by ‘{APPNAME}’,\n# Do not modify this file!\n# it may be overriden during updates\n{nix}"
            await sleep(0)
            return nix

        async def _write_config(nix: str):
            async with open(self.file, "w") as f:
                await f.write(nix)
                return nix

        async def _pos_write_fixup(*args):
            await nixformat(self.file)
            async with open(self.file, "r") as f:
                return await f.read()

        steps: list[tuple[str, Any]] = [
            ("generating config", _generate_config),
            ("removing imports", _pre_write_fixup),
            ("writing to file", _write_config),
            ("cleaning file", _pos_write_fixup),
        ]
        if self._display:
            async with Progress("auto-detecting hardware config") as progress:
                for step in steps:
                    with progress.info(step[0]):
                        hardwareconfig = await step[1](hardwareconfig)
                        await sleep(0.1)
        else:
            # no display, no need to sleep for beautiful display
            for step in steps:
                await step[1](hardwareconfig)
