name: 'Pull Request'

description: 'Create a pull request and merge it'

inputs:
  assignee:
    description: 'who to assign PR to'
    required: false
    default: 'MadMcCrow'
  commit:  
    description: 'commit message'
    required: false
    default: ':robot: github action'
  pr_title:  
    description: 'Pull request title'
    required: false
    default: ':robot: github action'
  pr_message:  
    description: 'Pull request body message'
    required: false
    default: ':robot: github action on $(date -I)'

runs:
  using: "composite"
  steps:
    - name: Create and merge PR
      run: |
          git switch -c updates-${{ github.run_id }}
          git commit -am "${{ inputs.commit }}"
          git push -u origin updates-${{ github.run_id }}
          PR=$(gh pr create \
            --assignee ${{ inputs.assignee }} \
            --base main \
            --body "${{inputs.pr_message}}" \
            --fill \
            --label bot \
            --title "Auto update $(date -I)")
          gh pr merge $PR --merge --delete-branch
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
