name: 'Setup environment'

description: 'Clone repo and install nix'

runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v3
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
     - name: Set up git
        run: |
          git config user.email gnoe.perard+git@gmail.com
          git config user.name "Git Bot"