[project]
name        = "ostool"
version     = "0.1.0"
description = "Tools for installing and updating nonOS systems"
authors = [{ name = "MadMcCrow", email = "do-not-mail.me@please.com" }]
# TODO : add a readme in docs !
# readme      = "README.md"
requires-python = ">=3.14"
dependencies    = [ "cmd", "tui"]


[project.scripts]
os = "ostool:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
compile-bytecode = true

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
cmd = { workspace = true}
tui = { workspace = true}

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = [
    "EXE001", # file has shebang but not executable
    "I001",   # imports are unsorted
    "UP037"   # quoted annotations (instead of from __future__ import annotations)
]
