name: 'Setup nix'

description: 'install nix'

runs:
  using: "composite"
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          auto-optimise-store = true
          access-tokens = github.com=${{ github.token }}
          experimental-features = nix-command flakes
          substituters = https://cache.nixos.org/ https://nix-community.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
        install_url: https://releases.nixos.org/nix/nix-2.12.0/install