name: Flake Update


on: 
  push:
  schedule:
    - cron: '0 2 * * *'

jobs:

  # generate JSONs for future builds and checks
  generate_matrix:
    runs-on: ubuntu-20.04
    outputs:
      packages: ${{ steps.gen_packages.outputs.packages }}
      checks: ${{ steps.gen_checks.outputs.checks }}
    steps :
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup-nix
        uses: ./.github/actions/setup-nix
      - name: Generate flake.json
        run: |
          nix flake show --json > flake.json
      - id: gen_packages
        run: |
          packages=$(jq -c '.packages."x86_64-linux" | keys' < flake.json)
          printf "::set-output name=packages::%s" "$packages"
      - id: gen_checks
        run: |
          checks=$(jq -c '.checks."x86_64-linux" | keys' < flake.json)
          printf "::set-output name=checks::%s" "$checks"

  # update flake inputs
  update_flake:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup-nix
        uses: ./.github/actions/setup-nix
      - name: Update the flake
        run: nix flake update
      - name: Store flake.lock
        uses: actions/upload-artifact@v3
        with:
          name: flake_lock
          path: flake.lock

  # build new flake 
  build_flake:
    runs-on: ubuntu-20.04
    needs: [generate_matrix, update_flake]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        package: ${{fromJson(needs.generate_matrix.outputs.packages)}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup-nix
        uses: ./.github/actions/setup-nix
      - name: Set up cachix
        uses: cachix/cachix-action@master # pathsToPush, please update once we have v11!
        with:
          name: MadMcCrow
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          pathsToPush: result
      - name: Restore flake.lock
        uses: actions/download-artifact@v3
        with:
          name: flake_lock
      - name: Build everything
        run: |
          nix build .#${{ matrix.package }}

  # perform the necessary checks that'll ensure we can run this config
  build_checks:
    runs-on: ubuntu-20.04
    needs: [generate_matrix, update_flake]
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        check: ${{fromJson(needs.generate_matrix.outputs.checks)}}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup-nix
        uses: ./.github/actions/setup-nix
      - name: Set up cachix
        uses: cachix/cachix-action@master # pathsToPush, please update once we have v11!
        with:
          name: MadMcCrow
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          skipPush: true
      - name: Restore flake.lock
        uses: actions/download-artifact@v3
        with:
          name: flake_lock
      - name: Build everything
        run: |
          nix build .#checks.x86_64-linux.${{ matrix.check }} --no-link

  #
  check_flake:
    runs-on: ubuntu-20.04
    needs: [update_flake]
    continue-on-error: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: setup-nix
        uses: ./.github/actions/setup-nix
      - name: Restore flake.lock
        uses: actions/download-artifact@v3
        with:
          name: flake_lock
      - name: Build everything
        run: |
          nix flake check --keep-going

  # Create pull request
  push_update:
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: [update_flake, build_flake, build_checks, check_flake]
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Restore flake.lock
      uses: actions/download-artifact@v3
      with:
        name: flake_lock
    - name: Set up git
      run: |
        git config user.email gnoe.perard+git@gmail.com
        git config user.name "Git Bot"
    - id: pull-request
      uses: ./.github/actions/pull-request
      with: 
        commit:   ':robot::snowflake: flake.lock : update'
        pr_title: ':robot::snowflake: update flake lock '
